"use client";
import React, { useEffect, useMemo, useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Bug, CheckCircle2, ChevronLeft, ChevronRight, CircleDot, GitCommitHorizontal, GitFork, GitMerge, Pause, Play, Rocket, Sparkles } from "lucide-react";

const fallback = [
  { sha:"a91bc4e", message:"chore: scaffold real-time collaboration workspace", date:"2024-08-02", repository:"Bright-Code", kind:"commit", url:"#" },
  { sha:"e48a7fd", message:"feat: add Monaco editor and room presence", date:"2024-08-18", repository:"Bright-Code", kind:"feature", url:"#" },
  { sha:"c2f901b", message:"fix: resolve concurrent editor update conflict", date:"2024-09-02", repository:"Bright-Code", kind:"fix", url:"#" },
  { sha:"d8ab132", message:"ci: add production build verification", date:"2024-09-10", repository:"Bright-Code", kind:"ci", url:"#" },
  { sha:"ff04d91", message:"merge: ship collaborative IDE v1", date:"2024-09-12", repository:"Bright-Code", kind:"merge", url:"#" },
  { sha:"3b7ea04", message:"feat: add ARIMA demand forecast API", date:"2024-10-05", repository:"DemandSight", kind:"feature", url:"#" },
];
const types = {
  feature: { label:"FEATURE UNLOCKED", color:"var(--color-sage)", icon:Sparkles, copy:"A capability enters the product and expands what users can do." },
  fix: { label:"BUG CONTAINED", color:"var(--color-error)", icon:Bug, copy:"A production edge case becomes a durable engineering lesson." },
  ci: { label:"PIPELINE GREEN", color:"var(--color-sky)", icon:CheckCircle2, copy:"Automation takes over a repeatable delivery check." },
  merge: { label:"MILESTONE SHIPPED", color:"var(--color-lavender)", icon:GitMerge, copy:"The branch resolves into a visible product milestone." },
  commit: { label:"BUILD LOG", color:"var(--color-gold)", icon:GitCommitHorizontal, copy:"An incremental decision moves the system forward." },
};
const formatDate = (value) => new Intl.DateTimeFormat("en", { month:"short", day:"numeric", year:"numeric" }).format(new Date(value));

export default function CommitStory({ audio }) {
  const [commits, setCommits] = useState(fallback), [source, setSource] = useState("curated"), [active, setActive] = useState(fallback.length - 1), [playing, setPlaying] = useState(false);
  useEffect(() => { let alive = true; fetch("/api/github/timeline").then((r) => r.ok ? r.json() : Promise.reject()).then((data) => { if (alive && data.commits?.length) { setCommits(data.commits); setActive(data.commits.length - 1); setSource("github"); } }).catch(() => {}); return () => { alive = false; }; }, []);
  useEffect(() => { if (!playing) return undefined; const timer = window.setInterval(() => setActive((value) => (value + 1) % commits.length), 2600); return () => window.clearInterval(timer); }, [playing, commits.length]);
  const commit = commits[active] || commits[0], type = types[commit.kind] || types.commit, EventIcon = type.icon;
  const projectCount = useMemo(() => new Set(commits.map((item) => item.repository)).size, [commits]);
  const select = (index) => { setActive(index); setPlaying(false); audio?.playClick(); };
  return <section id="commit-story" style={{ padding:"6rem 0", background:"linear-gradient(180deg, var(--color-bg-darker), var(--color-bg)", borderTop:"1px solid var(--border-subtle)" }}><div className="container">
    <div style={{ display:"flex", alignItems:"end", justifyContent:"space-between", gap:"1rem", flexWrap:"wrap", marginBottom:"2rem" }}><div style={{ maxWidth:670 }}><div className="font-sans-title" style={{ color:"var(--color-rose)", marginBottom:"0.55rem" }}>04 / COMMIT STORY MODE</div><h2 style={{ fontSize:"clamp(2rem, 4vw, 3.5rem)", margin:0 }}>Every ship has a <span style={{ color:"var(--color-wine)" }}>story.</span></h2><p style={{ margin:"0.8rem 0 0", maxWidth:600 }}>A cinematic replay of GitHub history—features, fixes, pipeline checks, and the moments they become a product.</p></div><div style={{ fontFamily:"var(--font-mono)", fontSize:"0.63rem", color:"var(--color-comment)", textAlign:"right" }}><div style={{ color:source === "github" ? "var(--color-sage)" : "var(--color-gold)", marginBottom:4 }}>● {source === "github" ? "LIVE PUBLIC GITHUB LOG" : "CURATED STORY / LIVE LOG OFFLINE"}</div>{commits.length} beats · {projectCount} repositories</div></div>
    <div className="commit-story-grid"><div className="commit-stage"><div style={{ display:"flex", alignItems:"center", justifyContent:"space-between", gap:"1rem", paddingBottom:"1rem", borderBottom:"1px solid var(--border-subtle)" }}><span style={{ fontFamily:"var(--font-mono)", fontSize:"0.64rem", color:"var(--color-comment)" }}>NOW REPLAYING · {String(active + 1).padStart(2, "0")} / {String(commits.length).padStart(2, "0")}</span><button aria-label={playing ? "Pause story" : "Play story"} className="commit-play" onClick={() => { setPlaying((value) => !value); audio?.playClick(); }}>{playing ? <Pause size={14}/> : <Play size={14}/>} {playing ? "PAUSE" : "PLAY STORY"}</button></div><AnimatePresence mode="wait"><motion.div key={`${commit.sha}-${active}`} initial={{ opacity:0, y:12 }} animate={{ opacity:1, y:0 }} exit={{ opacity:0, y:-10 }} transition={{ duration:0.24 }} style={{ padding:"2.2rem 0 1.2rem" }}><div style={{ display:"inline-flex", alignItems:"center", gap:"0.42rem", color:type.color, fontFamily:"var(--font-mono)", fontSize:"0.66rem", letterSpacing:"0.08em", fontWeight:700 }}><EventIcon size={14}/> {type.label}</div><h3 style={{ fontFamily:"var(--font-mono)", fontSize:"clamp(1.2rem, 2.5vw, 2rem)", lineHeight:1.45, margin:"1rem 0 0.9rem" }}>{commit.message}</h3><p style={{ maxWidth:640, fontSize:"0.92rem", margin:0 }}>{type.copy}</p><div style={{ display:"flex", gap:"0.65rem", flexWrap:"wrap", marginTop:"1.5rem", fontFamily:"var(--font-mono)", fontSize:"0.68rem" }}><span className="commit-chip"><GitCommitHorizontal size={12}/> {commit.repository}</span><span className="commit-chip">#{commit.sha}</span><span className="commit-chip">{formatDate(commit.date)}</span></div>{commit.url !== "#" && <a href={commit.url} target="_blank" rel="noreferrer" className="commit-link"><GitFork size={13}/> Inspect this commit</a>}</motion.div></AnimatePresence><div style={{ display:"flex", justifyContent:"space-between", borderTop:"1px solid var(--border-subtle)", paddingTop:"1rem" }}><button className="commit-nav" onClick={() => select((active - 1 + commits.length) % commits.length)}><ChevronLeft size={15}/> Previous</button><button className="commit-nav" onClick={() => select((active + 1) % commits.length)}>Next <ChevronRight size={15}/></button></div></div><div className="commit-timeline" aria-label="Commit timeline">{commits.map((item, index) => { const itemType = types[item.kind] || types.commit, ItemIcon = itemType.icon; return <button key={`${item.sha}-${index}`} className={`commit-beat ${active === index ? "active" : ""}`} onClick={() => select(index)}><span className="commit-rail" style={{ "--beat-color":itemType.color }}><ItemIcon size={13}/></span><span style={{ minWidth:0, flex:1, textAlign:"left" }}><span className="commit-beat-title">{item.message}</span><span className="commit-beat-meta">{item.repository} · {formatDate(item.date)}</span></span>{active === index && <CircleDot size={14} color={itemType.color}/>}</button>; })}</div></div>
    <div style={{ display:"flex", gap:"1.2rem", flexWrap:"wrap", marginTop:"1rem", fontFamily:"var(--font-mono)", fontSize:"0.61rem", color:"var(--color-comment)" }}><span><Sparkles size={12} color="var(--color-sage)" style={{ verticalAlign:"middle" }}/> feature</span><span><Bug size={12} color="var(--color-error)" style={{ verticalAlign:"middle" }}/> fix</span><span><CheckCircle2 size={12} color="var(--color-sky)" style={{ verticalAlign:"middle" }}/> CI</span><span><Rocket size={12} color="var(--color-lavender)" style={{ verticalAlign:"middle" }}/> merge / milestone</span></div>
  </div></section>;
}