"use client";

import React, { useState } from "react";
import { ArrowRight, Lightbulb, RotateCcw, X } from "lucide-react";

const EXHIBITS = [
  { id:"forecast", project:"Run-Rate Forecaster", title:"Model-first forecasting", before:"Starting with model selection before defining the operational decision and error measure.", after:"Anchor experiments in the forecast horizon, backtesting loop, and business metric first.", lesson:"A model is only useful when its output changes a decision." },
  { id:"realtime", project:"BrightCode", title:"Transport without interface state", before:"Treating real-time collaboration as only a socket connection problem.", after:"Design explicit room, presence, permission, reconnect, and conflict states in the UI.", lesson:"Real-time products earn trust by showing what the system knows." },
  { id:"maps", project:"DemandSight", title:"Map before data contract", before:"Building visual overlays before defining the prediction payload and API boundaries.", after:"Establish a stable data contract, then let the map render predictable forecast data.", lesson:"Visual complexity becomes manageable when the data shape is boring." },
];

export default function FailureMuseum({ audio }) {
  const [open, setOpen] = useState(EXHIBITS[0].id);
  const exhibit = EXHIBITS.find((item) => item.id === open);

  return <section id="failure-museum" style={{ background:"var(--color-bg)", borderTop:"1px solid var(--border-subtle)", padding:"6rem 0" }}><div className="container"><div style={{ display:"flex", justifyContent:"space-between", gap:"1rem", alignItems:"end", flexWrap:"wrap", marginBottom:"1.7rem" }}><div style={{ maxWidth:720 }}><div className="font-sans-title" style={{ color:"var(--color-amber)", marginBottom:"0.6rem" }}>FAILURE MUSEUM</div><h2 style={{ margin:0, fontSize:"clamp(2rem,4vw,3.5rem)" }}>Early ideas, better <span style={{ color:"var(--color-amber)" }}>systems.</span></h2><p style={{ margin:"0.8rem 0 0" }}>A small collection of approaches I would not repeat—and the engineering habits they produced.</p></div><div style={{ color:"var(--color-comment)", fontFamily:"var(--font-mono)", fontSize:"0.65rem" }}>03 EXHIBITS / OPEN FOR INSPECTION</div></div><div style={{ display:"grid", gridTemplateColumns:"repeat(3, minmax(0,1fr))", gap:"0.8rem" }} className="museum-grid">{EXHIBITS.map((item, index) => <button key={item.id} onClick={() => { setOpen(item.id); audio?.playClick(); }} onMouseEnter={() => audio?.playHover()} className="glass-card" style={{ padding:"1.1rem", textAlign:"left", cursor:"pointer", background:open === item.id ? "var(--color-bg-elevated)" : "var(--color-bg-card)", border:`1px solid ${open === item.id ? "var(--color-amber)" : "var(--border-subtle)"}` }}><div style={{ color:"var(--color-comment)", fontFamily:"var(--font-mono)", fontSize:"0.62rem" }}>EXHIBIT 0{index + 1} / {item.project}</div><X size={19} color="var(--color-amber)" style={{ margin:"1rem 0 0.7rem" }}/><h3 style={{ margin:0, fontSize:"1.1rem", lineHeight:1.25 }}>{item.title}</h3><span style={{ display:"flex", alignItems:"center", gap:"0.3rem", color:"var(--color-amber)", fontFamily:"var(--font-mono)", fontSize:"0.65rem", marginTop:"1rem" }}>Inspect <ArrowRight size={12}/></span></button>)}</div><article className="glass-card" style={{ marginTop:"0.8rem", padding:"1.25rem", borderLeft:"3px solid var(--color-amber)" }}><div style={{ display:"grid", gridTemplateColumns:"1fr 1fr 1fr", gap:"1rem" }} className="museum-detail-grid"><div><div className="font-sans-title" style={{ color:"var(--color-wine)", marginBottom:"0.5rem" }}>Abandoned approach</div><p style={{ margin:0, fontSize:"0.85rem" }}>{exhibit.before}</p></div><div><div className="font-sans-title" style={{ color:"var(--color-sky)", marginBottom:"0.5rem" }}><RotateCcw size={12} style={{ verticalAlign:"middle" }}/> Pivot</div><p style={{ margin:0, fontSize:"0.85rem" }}>{exhibit.after}</p></div><div><div className="font-sans-title" style={{ color:"var(--color-amber)", marginBottom:"0.5rem" }}><Lightbulb size={12} style={{ verticalAlign:"middle" }}/> Lesson</div><p style={{ margin:0, fontSize:"0.85rem" }}>{exhibit.lesson}</p></div></div></article></div></section>;
}